### PR TITLE
Create build system

### PR DESCRIPTION
**Pull request by ianks**
When I visited HackCU today to check it out it to 30sec(!) to load the page. Everything looks super pro, and I wouldn't want people to get impatient so I decided to help out.

This pull request introduces some basic build tasks for the site. Overall, I was able to introduce a 57% savings on image size which should significantly help loading time (the current bottleneck). It also introduces a dev server, and a server to preview the distribution build. 

Better taught by example:

```python
$ gulp serve        #=> run dev server

$ gulp serve:dist   #=> build site (compile images, etc.) and the serve them

$ gulp              #=> build the site
```

The next important thing I think will be serving this site (or at least the images) on a CDN. Since this site is fully static, that best way to go.

Site is looking solid boys. Pumped for HackCU :yellow_heart:

### CODE REVIEW

**Comment by ianks** [comment]
UPDATE: Added some tasks to reduce the image size of the larger graphics. This cut down on the size anywhere from 2x-10x. More can still be done on that front too but I just went and attacked the biggest culprints (`judges/*` and `header-bg`, namely).

**Comment by Zandrr** [comment]
Looks good to me, thanks for helping out Ian!

**Comment by Zandrr** [comment]
went ahead and made you a collaborator :smile:

**Comment by ianks** [comment]
Thanks @Zandrr! My next mission is to put all the images on a CDN. Then we need to get @dawsonbotsford to push it into prod :smile:

**Comment by dawsonbotsford** [comment]
Pushed it live already!

**Comment by ianks** [comment]
Yeah man, I'm actually building out the functionality in Gulp to do that right now. Here's the basic process:

1. It goes through each file in the project
1. Hashes the content of the file (this makes sure that new changes invalidate the cache, and that users get the new files as opposed to the ones that were cached before)
1. Upload files to an Amazon s3 bucket
1. Server them through an Amazon Cloudfront CDN

**Pull request merged**
