### PR TITLE
Use png for logo image [resolves #44]

### LINKED ISSUE #44: render a high-quality PNG
To fix the CDN Warping

### PR DESCRIPTION
**Pull request by ianks**
Preview is available here: http://d1ma16vmjy33ld.cloudfront.net/

Let me know what you think @dawsonbotsford @alexwalling

### CODE REVIEW

**Comment by dawsonbotsford** [comment]
Looks good, but no favicon?

**Comment by ianks** [comment]
Nice catch. Pushing a fix now.

**Comment by ianks** [comment]
Fix'd

**Comment by dawsonbotsford** [comment]
Beautiful, looks very solved to me! I can redirect the DNS whenever. Is their an IP or a URL to redirect to?

**Comment by ianks** [comment]
You can just CNAME it to this: http://d1ma16vmjy33ld.cloudfront.net/

**Comment by dawsonbotsford** [comment]
I'm not about to take down the site on accident, is there a time today or tomrrow you can meet in person @ianks? I am pretty free in the mornings.

**Pull request merged**
